In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("/home/cj/Documents/MSci Final Project Code/temp/SolarFlare-Prediction/data/dataverse_files/forecastmodel_summary.csv")

In [4]:
df

,Unnamed: 0,Target,Mean_MAE,Mean_RMSE,Mean_NRMSE,Mean_R2,Std_RMSE,N_Features
0,5,R_VALUE,2.066120e-02,6.629788e-02,0.137204,0.969999,6.035026e-02,187
1,4,ABSNJZH,4.441002e+01,9.236902e+01,0.169148,0.961145,1.041782e+02,187
2,3,TOTUSJZ,2.992190e+12,6.091025e+12,0.183875,0.940573,6.713804e+12,187
3,0,TOTUSJH,2.597600e+02,4.730788e+02,0.232138,0.922106,4.227834e+02,187
4,1,TOTBSQ,4.442330e+09,8.008721e+09,0.264905,0.871255,7.765100e+09,187
5,2,TOTPOT,9.791870e+22,1.778955e+23,0.295494,0.854778,1.467152e+23,187

In [6]:
df = df.drop(columns=["Unnamed: 0"])
df.to_html("forecastmodelsummary.html", index=False)

In [7]:
df = pd.read_csv("features_descriptions.csv")

In [8]:
df

   Features                                        Description
0   ABSNJZH  Absolute value of the net current helicity in ...
1      EPSX     Sum of X-component of normalized Lorentz force
2      EPSY     Sum of Y-component of normalized Lorentz force
3      EPSZ     Sum of Z-component of normalized Lorentz force
4   MEANALP                               Mean twist parameter
5   MEANGAM                             Mean inclination angle
6   MEANGBH        Mean value of the horizontal field gradient
7   MEANGBT             Mean value of the total field gradient
8   MEANGBZ          Mean value of the vertical field gradient
9   MEANJZD                      Mean vertical current density
10  MEANJZH                              Mean current helicity
11  MEANPOT   Mean photospheric excess magnetic energy density
12  MEANSHR                                   Mean shear angle
13  R_VALUE  Total unsigned flux around high gradient polar...
14  SAVNCPP  Sum of the absolute value of the net current p...
15  SHRGT45      Area with shear angle greater than 45 degrees
16   TOTBSQ                   Total magnitude of Lorentz force
17    TOTFX                Sum of X-component of Lorentz force
18    TOTFY                Sum of Y-component of Lorentz force
19    TOTFZ                Sum of Z-component of Lorentz force
20   TOTPOT         Total photospheric magnetic energy density
21  TOTUSJH                    Total unsigned current helicity
22  TOTUSJZ                    Total unsigned vertical current
23   USFLUX                    Total unsigned flux in Maxwells

In [9]:
df.to_html("feature_descriptions.html",index=False)